### PR TITLE
Add inertia weight parameter for PSO optimizer

### PR DESCRIPTION
**Pull request by ajikmr**
Added inertia weight parameter for PSO optimizer. This parameter can have fixed value for a run or can decay with iterations. Learning factors 1 and 2 have been changed accordingly.

Parameter would give users more control over the optimization run behavior. This is similar to commit made on FieldOpt repo.

Reference: Inertia weight control strategies for particle swarm optimization ( https://www.researchgate.net/publication/309658844_Inertia_weight_control_strategies_for_particle_swarm_optimization_Too_much_momentum_not_enough_analysis )

### CODE REVIEW

**Comment by Bellout** [comment]
Hi Ajit, 
sorry the great delay. I realize this PR is quite outdated; they'll be a lot of conflicts because of a many changes to the current dev branch. Can you resubmit?

**Comment by ajikmr** [comment]
Hello Mathias, Yes. I think it will be better to resubmit. I will do it in a few days.
Ajit.

**Comment by Bellout** [comment]
Actually Ajit, even better: I'm running a realistic ICD and control optimization case using multiple configurations of the current PSO against other derivative-free algorithms (pattern-search and model-based). I see a clear decline in performance for increased dimensionality when using the canonical PSO. 

Let me know if you want me to benchmark some of your PSO algorithm versions on this case, to see if they can rival the performance of the other approaches.

**Comment by ajikmr** [comment]
That sounds great Mathias. Actually if you can somehow ignore 'CMA_ES.cpp delete step', then you can pull this version itself. 

It will be interesting to see how this PSO version compares with standard PSO version.

**Comment by ajikmr** [comment]
Made a fresh pull request.

**Pull request closed without merging**
